[book]
authors = ["Gábor Szabó"]
language = "en"
src = "pages"
title = "The warp by examples book"
description = ""

# Add github icon to the menu
[output.html]
git-repository-icon = "fa-github"
#git-repository-url = "https://github.com/seanmonstar/warp"
#edit-url-template = "https://github.com/seanmonstar/warp/edit/main/book/{path}"
git-repository-url = "https://github.com/szabgab/warp/tree/book"
edit-url-template = "https://github.com/szabgab/warp/blob/book/book/{path}"

# Embedding and the footer
[preprocessor.embedify]
footer.enable = true
footer.message = "Copyright © 2025 • Created with ❤️ by the authors of warp and [Gabor Szabo](https://szabgab.com/)"

